name: CI / CD Pipeline

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Prepare Environment
        run: |
          npm install
          npx playwright install
      - name: Run tests
        run: |
          npm run test
      - name: Check docs generation
        run: |
          npm rum doc:build
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Prepare Environment
        run: |
          npm install
      - name: Generate docs
        run: |
          npm run doc:build
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
